Fix AttributeError: 'int' object has no attribute 'node' due to constant prop
Fixes https://github.com/pytorch/pytorch/issues/140625

Signed-off-by: Edward Z. Yang <ezyang@meta.com>

ghstack-source-id: a9f9ee5a512b3a424e200b43eb991b6256b137cd
Pull Request resolved: https://github.com/pytorch/pytorch/pull/141250